version: "3"  # 使用Docker Compose 3的版本

services:  # 定义服务
  db:  # 数据库服务
    image: postgres:15-alpine  # 使用 PostgreSQL 15的Alpine版镜像
    environment:  # 环境变量设置
      POSTGRES_DB: wiki  # 设置数据库名称为wiki
      POSTGRES_PASSWORD: wikijsrocks  # 设置数据库密码为wikijsrocks
      POSTGRES_USER: wikijs  # 设置数据库用户名为wikijs
    logging:  # 配置日志
      driver: "none"  # 禁用日志记录
    restart: unless-stopped  # 容器退出时会自动重启
    volumes:  # 持久化存储
      - db-data:/var/lib/postgresql/data  # 将数据存储在`db-data`卷中，让数据库持久化

  wiki:  # Wiki.js 服务
    image: ghcr.io/requarks/wiki:2  # 使用Wiki.js的Docker镜像（版本2）
    depends_on:  # 配置依赖关系，确保数据库服务先启动
      - db
    environment:  # 设置Wiki.js连接数据库的环境变量
      DB_TYPE: postgres  # 数据库类型为PostgreSQL
      DB_HOST: db  # 数据库主机设置为 db（即服务名称）
      DB_PORT: 5432  # 数据库端口为 5432
      DB_USER: wikijs  # 数据库用户名
      DB_PASS: wikijsrocks  # 数据库密码
      DB_NAME: wiki  # 数据库名称
    restart: unless-stopped  # 容器退出时会自动重启，除非手动停止
    ports:
      - "8010:3000"  # 将容器内的3000端口映射到宿主机的8010端口，方便访问Wiki.js

volumes:  # 定义Docker卷
  db-data:  # 定义用于数据库持久化数据的卷
